### ISSUE TITLE
Crash on First Load

### ISSUE THREAD

**Issue by Spazmunki13** [dizzyd/prospects#1]
Hello, I just installed your mod and I get this crash as the game is loading.

https://openeye.openmods.info/crashes/59bb69d435579fc39e46d9393c5dda70

**Comment by dizzyd** [comment]
Hi @Spazmunki13 - thanks for the report! How did you install this pack? Do you have a manifest or some way I can reproduce this precise setup?

**Comment by Spazmunki13** [comment]
It's a custom pack that I am working on for a friend and me.

This is the list of mods if that helps:
https://www.modlister.com/user/Spazmunki13

**Comment by dizzyd** [comment]
Hi @Spazmunki13 - I just released 1.0.1 which _should_ fix this bug. Let me know if it doesn't, please. :)

**Comment by Spazmunki13** [comment]
Seems to all be working now. Thanks for the quick fix! :)
