### ISSUE TITLE
Flowers Spawn Anywhere

### ISSUE THREAD

**Issue by Spazmunki13** [dizzyd/prospects#4]
I'm noticing that the flowers spawn pretty much anywhere, on any block. I've spotted them on sand, and at the bottom of bodies of water.

This is what it looks like with Realistic Item Drops installed:
https://imgur.com/FPCnbM8

Hehe!

**Comment by dizzyd** [comment]
Hi @Spazmunki13! You are correct; I missed a check for air blocks. :) This will be fixed in the next release.
