### ISSUE TITLE
[Suggestion] Support for Geolosys ores

### ISSUE THREAD

**Issue by scottosx** [dizzyd/prospects#5]
I did see the discussion about this on CurseForge but thought I would 'formalize' a request.

Geolosys is a ore generation system similar to that in TerraFirmaCraft where ores are spawned in large clusters.However, they are not the vanilla ore blocks but the mod's blocks have standaridized ore dictionary entries. 

Currently, they are marked with clusters on the surface which is fine. Flowers would be a nice addition too. Thus, the pairing of your mod with Geolosys out the box would probably get more user interest as they would not have to configure it at first as there is already this ore clustering system.

https://minecraft.curseforge.com/projects/geolosys?gameCategorySlug=mc-mods&projectID=271856

**Comment by dizzyd** [comment]
Let me make sure I understand what you're asking for here - you'd like Prospects flower to generate when a corresponding Geolosys deposit is found? This might mean you get both Geolosys samples AND the ore flowers -- is that what you want?

**Comment by scottosx** [comment]
Yes. I think that would be ok. Your flowers are viewable from a distance. Also, the samples in the Geolosys config can be reduced to 1 per chunk.

**Comment by dizzyd** [comment]
@scottosx - OK, I added support for Geolosys. It's not as clean as I hoped, due to the way that items/blocks work in that mod, but it does work. :) Will cut a release in next few days.

**Comment by scottosx** [comment]
Thanks for adding support. I am still waiting for a release that I can test.

**Comment by dizzyd** [comment]
Released in 1.0.3.
